db:
   image: mysql:5.5
   environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: nagiosql_user
      MYSQL_PASSWORD: nagiosql
      MYSQL_DATABASE: db_nagiosql_v32
docker-debian-nagios:
   build: .
   environment:
      NAGIOSADM_EMAIL: this.is.ignored@email.com 
      NAGIOSADM_PW: nagios
   ports:
      - "10080:80"
      - "10022:22"
   links:
      - db
